---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: runtime
    version: v1
  name: runtime
spec:
  replicas: 1
  selector:
    matchLabels:
      app: runtime
  serviceName: runtime
  template:
    metadata:
      labels:
        app: runtime
        version: v1
    spec:
      nodeName: misaka.com
      containers:
        - image: docker.io/kaixindeken/runtime
          imagePullPolicy: Always
          name: runtime-container
          command:
            - 'sh'
            - '-c'
            - '/root/runtime -c=/root/config.json'
          volumeMounts:
            - mountPath: /dev2
              name: input-storage
            - mountPath: /root/config.json
              name: dev-storage
      restartPolicy: Always
      volumes:
        - name: dev-storage
          hostPath:
            path: /dev2
        - name: config-storage
            hostPath:
              path: /root/config.json
